// Every comb plugin. Imported for the side effect of registering with core/registry.js.
import './blend.js'
import './switch.js'
import './gate.js'
import './route.js'
import './add.js'
import './maxmin.js'
import './stampn.js'
import './smax.js'
import './smin.js'
