"""Regenerate `references/index.md` from the documents' own OKF headers.

    python gaia/scripts/index.py            # write index.md
    python gaia/scripts/index.py --check    # fail if it is out of date, changing nothing

WHY THIS IS GENERATED AND NEVER WRITTEN BY HAND

`terrain-architect/references/00-index.md` grew to 716 lines and became a second SKILL.md --
a map so large it needed a map. It drifted from the corpus because nothing forced it not to.

Deriving it from the headers makes that impossible: the index cannot claim a document that
does not exist, cannot miss one that does, and cannot describe one differently from how the
document describes itself. `--check` in CI is what keeps it honest -- a hand edit shows up as
a diff, not as a slow divergence nobody notices.

This is also why `SKILL.md` must route by AXIS and TAG rather than listing documents: the
corpus is meant to grow, and a router that grows with it stops being a router.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from okf import Unparseable, documents, parse_front_matter  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "references" / "index.md"

# The order axes are presented in. A document's axis is its first tag that appears here; a
# document whose tags name no axis is reported rather than silently filed under "other",
# because a document nobody can route to is invisible.
AXES = [
    ("generation", "Generation — building the terrain"),
    ("simulation", "Simulation — processes over time"),
    ("rendering", "Rendering — drawing it"),
    ("architecture", "Architecture — how a tool is put together"),
    ("bibliography", "Provenance"),
]


def collect() -> tuple[dict[str, list[dict]], list[str]]:
    by_axis: dict[str, list[dict]] = {k: [] for k, _ in AXES}
    problems: list[str] = []
    for path in documents(ROOT):
        if path == INDEX:
            continue
        try:
            fm, _ = parse_front_matter(path)
        except Unparseable as e:
            problems.append(str(e))
            continue
        tags = fm.get("tags", []) or []
        axis = next((k for k, _ in AXES if k in tags), None)
        if axis is None:
            problems.append(f"{path.relative_to(ROOT)}: tags {tags} name no axis "
                            f"({', '.join(k for k, _ in AXES)}) -- it cannot be routed to")
            continue
        by_axis[axis].append({
            "file": path.name,
            "title": fm.get("title", path.stem),
            "description": fm.get("description", ""),
            "status": fm.get("status", "stable"),
            "verified": bool(fm.get("verified")),
            "tags": [t for t in tags if t != axis],
        })
    for rows in by_axis.values():
        rows.sort(key=lambda r: r["file"])
    return by_axis, problems


def render(by_axis: dict[str, list[dict]]) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    total = sum(len(v) for v in by_axis.values())
    verified = sum(1 for v in by_axis.values() for r in v if r["verified"])
    out = [
        "---",
        "type: Index",
        "title: Gaia index",
        'description: "Every Gaia document, its axis, and whether a human has checked its'
        ' citations."',
        "tags: [index, routing]",
        "status: draft",
        'okf_version: "0.2"',
        f"generated: {{ by: process:gaia-index, at: {stamp} }}",
        "---",
        "# Gaia index",
        "",
        "**Generated by `scripts/index.py`. Do not edit — your changes will be overwritten,",
        "and `--check` will fail in the meantime.**",
        "",
        f"{total} document(s). **{verified} have been checked by a human**; the rest are",
        "`draft`, meaning their citations are well-formed but nobody has confirmed the cited",
        "work says what the document claims. That distinction is the whole point of the",
        "`status` column — see `scripts/check.py --list`.",
        "",
    ]
    for key, heading in AXES:
        rows = by_axis.get(key) or []
        if not rows:
            continue
        out += [f"## {heading}", "", "| Document | What it answers | Status |", "|---|---|---|"]
        for r in rows:
            mark = "**checked**" if r["verified"] else r["status"]
            out.append(f"| [`{r['file']}`]({r['file']}) | {r['description']} | {mark} |")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if index.md is stale; write nothing")
    args = ap.parse_args()

    by_axis, problems = collect()
    if problems:
        for p in problems:
            print(f"  FAIL  {p}")
        print(f"\n{len(problems)} problem(s); index not written.")
        return 1

    want = render(by_axis)
    if args.check:
        have = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        # The timestamp changes every run, so comparing it would make --check always fail.
        # Compare everything else; a stale BODY is the drift that matters.
        strip = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith("generated:"))
        if strip(have) != strip(want):
            print("index.md is out of date. Run `python3 gaia/scripts/index.py`.")
            return 1
        print(f"index.md is current ({sum(len(v) for v in by_axis.values())} documents).")
        return 0

    INDEX.write_text(want, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)} — {sum(len(v) for v in by_axis.values())} documents")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
