// Generate the test bridge from the frozen contract in bridge-surface.json.
//
// WHY THIS EXISTS. Today the app is one inline classic <script>, so every top-level `let`/`const`/
// `function` is a real global and ~50 verification scripts reach them directly through
// page.evaluate. Bundling to ES modules scopes all of them, and the suite would go blind — not
// because behaviour changed, but because the instrument stopped reading, which is the worst failure
// mode available to the thing measuring a refactor.
//
// HOW IT WORKS. The emitted block is appended INSIDE the module, so its accessors close over the
// real module bindings. Three properties are load-bearing and each was proven before this was
// written:
//   1. `page.evaluate` bodies run in sloppy mode, so a bare `RES = 512` assigns to a property of the
//      global object — which lands on the setter and reaches the module binding.
//   2. Getters must return the LIVE object, never a copy: tests do `nodes.length = 0` and
//      `TYPES.blur.eval = ...`, and a copy would silently swallow both.
//   3. Symbols with no setter must THROW on assignment. A silent no-op would let a test believe it
//      had configured something it had not, and the assertion would then fail for the wrong reason.
//
// This bridge is migration scaffolding with a half-life, not a design. A 161-entry global API means
// any internal rename can break a test silently. Phase 8 replaces it with a curated
// `window.__STUDIO__` of ~15 entries once the specs no longer reach past it.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const surfacePath = resolve(here, '../../../terrain-architect/studio/bridge-surface.json')
// A SNIPPET for textual concatenation, NOT an importable module. This is not a style choice: an
// accessor like `() => RES` only reaches the real binding if it is lexically inside the module that
// declares it. Emitted as its own module and imported, every one of the 161 accessors would throw
// ReferenceError, because `RES` is not in the importing module's scope and ES modules have no
// mechanism to alias a live mutable binding into a foreign scope. So the Phase 3 extraction step
// appends this text to src/legacy.js after the app source.
const outPath = resolve(here, '../src/testing/bridge-block.js')

const surface = JSON.parse(readFileSync(surfacePath, 'utf8'))
const symbols = surface.symbols ?? []

// dom-id symbols are provided by the browser (an element id becomes a window property), so bridging
// them would shadow the live element with a stale reference.
const needed = symbols.filter((s) => s.kind !== 'dom-id')
const writable = needed.filter((s) => s.written)
const readonly = needed.filter((s) => !s.written)

const ident = /^[A-Za-z_$][A-Za-z0-9_$]*$/
const bad = needed.filter((s) => !ident.test(s.name))
if (bad.length) {
  console.error('Non-identifier symbols in surface, cannot bridge:', bad.map((s) => s.name))
  process.exit(1)
}

const q = (s) => JSON.stringify(s)
const L = []
L.push('/* GENERATED by scripts/generate-bridge.mjs from bridge-surface.json — do not edit.')
L.push(` * ${needed.length} symbols (${writable.length} writable, ${readonly.length} read-only).`)
L.push(' * Regenerate: npm run bridge:gen   Verify coverage: node _verify_bridge.js --check')
L.push(' *')
L.push(' * Appended to src/legacy.js AFTER the app source, so each accessor closes over the real')
L.push(' * module binding. It cannot be a separate importable module — see generate-bridge.mjs.')
L.push(' */')
// Dev and test only. Shipping 161 globals to production would make every internal name a public API.
L.push('if (import.meta.env && (import.meta.env.DEV || import.meta.env.MODE === "test")) {')
L.push('  const __t = globalThis')
L.push('  const __def = (name, get, set) => {')
L.push('    try {')
L.push('      Object.defineProperty(__t, name, { configurable: true, enumerable: false, get, set })')
L.push('    } catch (e) {')
// A symbol the host already defines non-configurably must be reported, never swallowed: a missing
// bridge entry is precisely what this phase must not hide.
L.push('      console.error("[bridge] cannot define " + name + ": " + (e && e.message))')
L.push('    }')
L.push('  }')
L.push('  const __ro = (name) => () => {')
L.push('    throw new TypeError("[bridge] " + name + " is read-only (const or function binding).")')
L.push('  }')
L.push('')
L.push(`  // ${writable.length} writable: tests assign these directly (RES = 512, nodes = [], ...).`)
for (const s of writable) {
  L.push(`  __def(${q(s.name)}, () => ${s.name}, (v) => { ${s.name} = v })`)
}
L.push('')
L.push(`  // ${readonly.length} read-only. Getters hand out the LIVE value: ${readonly.filter(s => s.patched).length} of`)
L.push('  // these are patched through by tests (TYPES.blur.eval = ..., gl.bindBuffer = ...), which a')
L.push('  // copy-returning getter would silently discard.')
for (const s of readonly) {
  L.push(`  __def(${q(s.name)}, () => ${s.name}, __ro(${q(s.name)}))`)
}
L.push('}')
L.push('')

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, L.join('\n'), 'utf8')
console.log(`bridge: ${needed.length} symbols -> ${outPath}`)
console.log(`        ${writable.length} writable, ${readonly.length} read-only, ` +
  `${symbols.length - needed.length} dom-id skipped, ` +
  `${needed.filter((s) => s.patched).length} patched-through`)
