#!/usr/bin/env python3
"""Renders the generated views in docs/ from data/. Never hand-edit a generated doc.

Usage: python3 scripts/render.py [--check]   (--check fails if docs are stale)
"""
import os
import sys

from model import MATURITY, ROOT, Model, sccs

DOCS = os.path.join(ROOT, "docs")
BANNER = "<!-- GENERATED by scripts/render.py from data/*.json — do not edit by hand -->\n\n"
MAT_BADGE = {"E": "", "M": " `emerging`", "X": " `experimental`", "S": " `speculative`"}


def cap_map(m):
    out = [BANNER, "# 01 · Engine Capability Map\n\n"]
    out.append("Everything required to build **and ship** the engine, decomposed as domain → area → capability. "
               "Each capability has exactly one owning skill (**bold**); contributors coordinate through the owner's contract. "
               "Maturity: unmarked = established production; `emerging` = shipping in some titles, evaluate per ADR; "
               "`experimental` = research, never an architectural baseline; `speculative` = watch only.\n\n")
    counts = {k: 0 for k in MATURITY}
    for cid in m.caps:
        counts[m.cap(cid)["maturity"]] += 1
    out.append(f"**{len(m.caps)} capabilities** in {len(m.domains)} domains — "
               + ", ".join(f"{counts[k]} {v}" for k, v in MATURITY.items()) + ".\n\n")
    out.append("## Domains\n\n| Domain | Areas | Capabilities |\n|---|---|---|\n")
    for d in m.domains:
        n = sum(len(a["caps"]) for a in d["areas"])
        out.append(f"| [{d['id']} · {d['name']}](#{d['id'].lower()}) | {len(d['areas'])} | {n} |\n")
    for d in m.domains:
        out.append(f"\n## {d['id']}\n\n### {d['name']}\n")
        for a in d["areas"]:
            out.append(f"\n**{a['id']} — {a['name']}**\n\n")
            for c in a["caps"]:
                cap = m.cap(c[0])
                contrib = f" · with {', '.join(cap['contributors'])}" if cap["contributors"] else ""
                out.append(f"- `{cap['id']}` {cap['name']}{MAT_BADGE[cap['maturity']]} — **{cap['owner']}**{contrib}\n")
    return "".join(out)


def dep_graph(m):
    out = [BANNER, "# 02 · Skill Dependency Graph\n\n"]
    out.append("Skills never depend on each other's internals; they depend on **contracts**. "
               "A skill depends on another skill exactly when it consumes a contract that skill owns. "
               "Contracts carry a layer (0 platform → 5 tools, P = process) and a build-level `requires` list that "
               "`check.py` proves acyclic and never upward. Runtime data may flow in both directions between "
               "subsystems (animation ↔ physics), but only through frame phases declared in `C-FRAME`.\n\n")
    # domain-level mermaid
    lead_of = {s: m.domain_lead(s) for s in m.skill_order}
    edges = m.skill_edges(include_universal=False, include_optional=False)
    dom_edges = {}
    for s, targets in edges.items():
        for t in targets:
            a, b = lead_of[s], lead_of[t]
            if a != b:
                dom_edges[(a, b)] = dom_edges.get((a, b), 0) + 1
    out.append("## Domain-level dependencies (required edges)\n\n")
    out.append("Nodes are top-level skills (a domain lead with its subtree, or a standalone cross-cutting skill). "
               "Edges are aggregated required contract dependencies between their subtrees; process contracts and "
               "universal runtime contracts (`C-ERR`, `C-MEM`, `C-INSTR`, `C-CRASH`, `C-BUDGET`) are omitted for legibility — every runtime skill consumes them.\n\n")
    out.append("```mermaid\nflowchart LR\n")
    tops = [s for s in m.skill_order if lead_of[s] == s and m.skill(s)["parent"] is not None]
    for t in tops:
        out.append(f"  {t.replace('-', '_')}[\"{m.skill(t)['name']}\"]\n")
    for (a, b), n in sorted(dom_edges.items()):
        out.append(f"  {a.replace('-', '_')} --> {b.replace('-', '_')}\n")
    out.append("```\n\n")

    # contracts table
    consumers = {c: [] for c in m.contracts}
    for s in m.skill_order:
        for cid, opt in m.deps(s, include_universal=False):
            consumers.setdefault(cid, []).append(s + ("?" if opt else ""))
    out.append("## Layered contract graph\n\n")
    for L in (0, 1, 2, 3, 4, 5, "P"):
        ids = [c for c in m.contracts if m.contract(c)["layer"] == L]
        out.append(f"- **L{L}** ({len(ids)}): " + ", ".join(f"`{c}`" for c in ids) + "\n")
    out.append("\n## Contracts\n\nFan-in counts explicit consumers (universal contracts are consumed implicitly by every runtime skill or every skill). "
               "High fan-in contracts are the **critical architectural contracts**: they are designed first, versioned under `C-API`, and changed only through the change-request protocol in `C-ORCH`.\n\n")
    out.append("`Oracle author` writes the contract's acceptance suite (`tests/acceptance/<contract>/`, read-only for "
               "implementers). Implementers are backends registered for the contract (per platform where marked).\n\n")
    out.append("| Contract | Layer | Owner | Implementers | Oracle author | Requires | Fan-in | Summary |\n|---|---|---|---|---|---|---|---|\n")
    rows = []
    for cid in m.contracts:
        c = m.contract(cid)
        u = c.get("universal")
        fan = f"universal ({u})" if u else str(len(consumers[cid]))
        rows.append((0 if u else -len(consumers[cid]), cid, c, fan))
    for _, cid, c, fan in sorted(rows, key=lambda r: (r[0], r[1])):
        impl = ", ".join(x for x in m.skill_order if cid in m.skill(x).get("implements", [])) or "—"
        out.append(f"| `{cid}` {c['name']} | {c['layer']} | {c['owner']} | {impl} | {c.get('oracle_author', '—')} | "
                   f"{', '.join(c['requires']) or '—'} | {fan} | {c['summary']} |\n")

    out.append("\n## Critical contracts (top fan-in, excluding universals)\n\n")
    ranked = sorted((cid for cid in m.contracts if not m.contract(cid).get("universal")),
                    key=lambda c: -len(consumers[c]))[:12]
    for cid in ranked:
        out.append(f"- `{cid}` ({len(consumers[cid])} consumers) — {m.contract(cid)['name']}: {', '.join(sorted(consumers[cid]))}\n")

    out.append("\n## Runtime coupling cycles\n\n")
    comps = sccs(m.skill_edges(include_universal=False, include_optional=False, code_only=True))
    if comps:
        out.append("Required-edge cycles between skills. Each must be mediated by a frame phase or event contract, never by a direct call:\n\n")
        for comp in comps:
            out.append(f"- {', '.join(comp)}\n")
    else:
        out.append("None among required edges.\n")

    out.append("\n## Per-skill dependencies\n\n| Skill | Provides | Runtime (required) | Runtime (optional) | Tool-side | Depends on skills |\n|---|---|---|---|---|---|\n")
    for s in m.skill_order:
        sk = m.skill(s)
        req = [d for d in sk["consumes"] if not m.parse_dep(d)[1]]
        opt = [d for d in sk["consumes"] if m.parse_dep(d)[1]]
        dep_sk = sorted(m.skill_edges(False, True, include_tool=True)[s])
        out.append(f"| {s} | {', '.join(sk['provides']) or '—'} | {', '.join(req) or '—'} | {', '.join(opt) or '—'} | {', '.join(sk['tool_consumes']) or '—'} | {', '.join(dep_sk) or '—'} |\n")
    return "".join(out)


def hierarchy(m):
    out = [BANNER, "# 03 · Skill Hierarchy\n\n"]
    tiers = {}
    for s in m.skill_order:
        tiers.setdefault(m.skill(s)["tier"], []).append(s)
    out.append(f"**{len(m.skills)} skills**: " + ", ".join(f"{len(v)} {k}" for k, v in tiers.items()) + ".\n\n")
    out.append("## Tree\n\n```\n")

    def walk(s, depth):
        sk = m.skill(s)
        tag = {"orchestrator": "[O]", "cross-cutting": "[X]", "lead": "[L]", "expert": "   "}[sk["tier"]]
        kind = {"runtime": "", "tool": " ·tool", "process": " ·process"}[sk["kind"]]
        out.append(f"{'    ' * depth}{tag} {s}  ({len(m.owned_caps(s))}){kind}\n")
        for ch in m.children(s):
            walk(ch, depth + 1)
    root = [s for s in m.skill_order if m.skill(s)["parent"] is None][0]
    walk(root, 0)
    out.append("```\n\n`[O]` orchestrator · `[X]` cross-cutting discipline · `[L]` domain lead · (n) = capabilities owned · "
               "·tool = ships only in the tools target · ·process = organizational, never in a build.\n\n")
    ws = {}
    for s_ in m.skill_order:
        ws.setdefault(m.skill(s_).get("workstream", "—"), []).append(s_)
    out.append("## Workstreams\n\nIntegration groups used for delegated arbitration and staffing (`ARCH.ORG.escalation`, `ARCH.ORG.staffing`).\n\n")
    for w, members in ws.items():
        out.append(f"- **{w}** ({len(members)}): {', '.join(members)}\n")

    out.append("\n## Configurations (scale-down proof)\n\n")
    out.append("A configuration is a point on three independent axes: scale/feature **profiles** (a base plus add-ons), a "
               "build **target** (client, headless-client, server, tools) and target **platforms**. `check.py` proves every "
               "configuration closed under its required dependencies (process skills excluded: they are organizational), "
               "and that contracts needing an implementer (the RHI) have one on every platform.\n\n")
    out.append("| Configuration | Profiles | Target | Platforms | Build skills | Capabilities |\n|---|---|---|---|---|---|\n")
    for n, c in m.configurations.items():
        ncap = sum(1 for cid in m.caps if m.cap_in_configuration(cid, n))
        out.append(f"| {n} | {', '.join(c['profiles'])} | {c['target']} | {', '.join(c.get('platforms', []))} | {len(m.members(n))} | {ncap} |\n")
    out.append("\n### Membership matrix\n\n")
    names = list(m.configurations)
    out.append("| Skill | " + " | ".join(names) + " |\n|---|" + "---|" * len(names) + "\n")
    for s in m.skill_order:
        if m.skill(s)["kind"] == "process":
            continue
        out.append(f"| {s} | " + " | ".join("●" if m.in_configuration(s, n) else "" for n in names) + " |\n")
    out.append("| **total** | " + " | ".join(str(len(m.members(n))) for n in names) + " |\n")

    out.append("\n## Skill cards\n")
    for s in m.skill_order:
        sk = m.skill(s)
        plats = f" · platforms: {', '.join(sk['platforms'])}" if sk.get("platforms") else ""
        tg = f" · targets: {', '.join(sk['targets'])}" if sk["targets"] else ""
        out.append(f"\n### {s}\n\n**{sk['name']}** · {sk['tier']} · {sk['kind']} · workstream: {sk.get('workstream','—')} · parent: {sk['parent'] or '—'} · profiles: {', '.join(sk['profiles'])}{tg}{plats}\n\n")
        out.append(f"{sk['purpose']}\n\n")
        owned = m.owned_caps(s)
        out.append("- **Owns:** " + "; ".join(f"`{c['id']}`" for c in owned) + "\n")
        contrib = m.contributed_caps(s)
        if contrib:
            out.append("- **Contributes to:** " + "; ".join(f"`{c['id']}`" for c in contrib) + "\n")
        out.append("- **Not responsible for:** " + "; ".join(f"{w} → {', '.join(o) if isinstance(o, list) else o}" for w, o in sk["non_responsibilities"]) + "\n")
        out.append(f"- **Provides:** {', '.join(sk['provides']) or '—'} · **Consumes:** {', '.join(sk['consumes']) or '—'}"
                   + (f" · **Tool-side:** {', '.join(sk['tool_consumes'])}" if sk['tool_consumes'] else "")
                   + (f" · **Implements:** {', '.join(sk['implements'])}" if sk['implements'] else "") + "\n")
        if sk.get("untrusted_inputs"):
            out.append(f"- **Untrusted inputs:** {', '.join(sk['untrusted_inputs'])}\n")
        out.append(f"- **Expertise:** {', '.join(sk['expertise'])}\n")
        out.append(f"- **Critics (G2):** {', '.join(m.critics_for(s, 'G2'))}\n")
    return "".join(out)


def crosscutting(m):
    out = [BANNER, "# 04 · Cross-Cutting Skills\n\n"]
    out.append("Cross-cutting disciplines own an **obligation** that every other skill must meet, and review every skill against it. "
               "They also own shared infrastructure where one exists (the instrumentation API, the test DoD, the budget contract). "
               "In phase 2, every generated SKILL.md must contain a section answering each obligation below, or state why it does not apply.\n\n")
    out.append("| Concern | Owner | Obligation on every skill |\n|---|---|---|\n")
    for c in m.cross_doc["concerns"]:
        out.append(f"| {c['concern']} | {c['owner']} | {c['obligation']} |\n")
    if m.cross_doc.get("independence"):
        out.append("\n## Independence matrix\n\nThese pairs are never hosted by the same agent at any organization tier "
                   "(`check.py` proves they sit in different workstreams, the co-hosting unit).\n\n| A | B | Why |\n|---|---|---|\n")
        for a, b, why in m.cross_doc["independence"]:
            out.append(f"| {a} | {b} | {why} |\n")
    out.append("\n## Cross-cutting and orchestration skills\n\n")
    for s in m.skill_order:
        sk = m.skill(s)
        if sk["tier"] in ("orchestrator", "cross-cutting"):
            out.append(f"- **{s}** ({sk['tier']}) — {sk['purpose']}\n")
    out.append("\n## Universal contracts\n\n")
    for cid in m.contracts:
        c = m.contract(cid)
        if c.get("universal"):
            out.append(f"- `{cid}` {c['name']} — consumed by {'every skill' if c['universal'] == 'all' else 'every runtime skill'}; owner {c['owner']}.\n")
    return "".join(out)


def critic_matrix(m):
    out = [BANNER, "# 05 · Critic Framework\n\n"]
    out.append("Critics are independent reviewers with one mandate each. They run blind (fresh context, no author rationale, no prior-round history) "
               "and report only concrete, material deficiencies. See `gauntlet/PROTOCOL.md` for the loop, severity scale and convergence rule.\n\n")
    out.append("## Stages\n\n")
    for k, v in m.critic_doc["stages"].items():
        out.append(f"- **{k}** — {v}\n")
    out.append("\n## Critics\n\n")
    for k, c in m.critics.items():
        out.append(f"### {k} · {c['name']}\n\n{c['mandate']}\n\n- Stages: {', '.join(c['stages'])}\n- Scope: {', '.join(c['scope'])}\n- Checks: " + "; ".join(c["checks"]) + "\n\n")
    out.append("## Coverage matrix (stage G2 — which critics review which SKILL.md)\n\n")
    ks = list(m.critics)
    out.append("| Skill | " + " | ".join(k[2:] for k in ks) + " |\n|---|" + "---|" * len(ks) + "\n")
    for s in m.skill_order:
        row = []
        for k in ks:
            c = m.critics[k]
            if "G2" not in c["stages"]:
                row.append("")
            elif m.scope_matches([x for x in c["scope"] if x != "all"], s):
                row.append("◆")
            elif "all" in c["scope"]:
                row.append("·")
            else:
                row.append("")
        out.append(f"| {s} | " + " | ".join(row) + " |\n")
    out.append("\n◆ domain critic (specifically scoped) · · universal critic\n")
    return "".join(out)


def radar_legacy_milestones(m):
    out = [BANNER, "# 09 · Technology Radar, Legacy Patterns & Milestones\n\n"]
    out.append("## Technology radar\n\nEvery non-established capability is on the radar with an owner, evidence, a revisit/promotion trigger and a fallback (`check.py` enforces it). Non-goals are recorded explicitly.\n\n")
    out.append("| Technology | Class | Owner | Capabilities | Evidence | Revisit when | Fallback |\n|---|---|---|---|---|---|---|\n")
    for e in sorted(m.radar_doc["entries"], key=lambda e: "ESMX".index(e["class"]) if e["class"] in "ESMX" else 9):
        caps = "non-goal" if e.get("non_goal") else ", ".join(f"`{c}`" for c in e["capabilities"])
        out.append(f"| {e['tech']} | {MATURITY[e['class']]} | {e['owner']} | {caps} | {e['evidence']} | {e['revisit']} | {e.get('fallback','—')} |\n")
    out.append("\n## Anti-legacy pattern catalogue\n\nA pattern is not forbidden. If it appears, the justification owner must record an ADR. K-LEGACY checks this at G2 and S1–S4.\n\n")
    out.append("| ID | Pattern | Detection hint | Default stance | Justification owner | Stance capabilities |\n|---|---|---|---|---|---|\n")
    for p in m.legacy_doc["patterns"]:
        sc = ", ".join(f"`{c}`" for c in p.get("stance_capabilities", []))
        out.append(f"| {p['id']} | {p['pattern']} | {p['detection']} | {p['default_stance']} | {p['justification_owner']} | {sc} |\n")
    out.append("\n## Untrusted-input registry\n\nEvery input class has exactly one validating owner; parser owners register it too. `harness` inputs are fuzz targets owned next to the parser (campaign policy in robustness-fuzzing); `redteam` inputs are text read by development agents, covered by the prompt-injection corpus (`XC.SEC.agent-redteam`). `check.py` enforces the registry.\n\n")
    out.append("| Input | Validating owner | Parser owners | Trust tier | Coverage | Limits |\n|---|---|---|---|---|---|\n")
    for i in m.untrusted_doc["inputs"]:
        out.append(f"| {i['id']} | {i['validating_owner']} | {', '.join(i.get('parser_owners', [])) or '—'} | {i['trust']} | {i['mode']} | {i['limits']} |\n")
    out.append("\n## Milestones (walking skeleton → engine 1.0)\n\n`check.py` proves: each milestone is closed over its own and earlier milestones' build skills; every configuration a milestone claims (optionally restricted to platforms, `name@pc`) has all its member skills built by then; every configuration is claimed in full exactly once; every build skill sits in exactly one milestone; every code contract is frozen exactly once, after its owner and at least one consumer exist and never before the contracts it requires; gates name existing capabilities.\n\n")
    for ms in m.milestone_doc["milestones"]:
        claims = ", ".join(f"`{c}`" for c in ms.get("configurations", [])) or "— (skeleton / release)"
        out.append(f"### {ms['id']} · {ms['name']} ({len(ms['skills'])} new build skills)\n\n**Configurations proven:** {claims}\n\n")
        out.append(f"**Exit criteria:** {ms['exit']}\n\n")
        if ms.get("gates"):
            out.append("**Gates (capability → independent validator):** " + ", ".join(
                f"`{g['capability']}` → `{g['validator']}`" for g in ms["gates"]) + "\n\n")
        if ms.get("contracts_frozen"):
            out.append(f"**Contracts frozen:** {', '.join(ms['contracts_frozen'])}\n\n")
        if ms.get("contracts_draft"):
            out.append(f"**Contracts drafted:** {', '.join(ms['contracts_draft'])}\n\n")
        out.append("Skills: " + ", ".join(ms["skills"]) + "\n\n")
    return "".join(out)


VIEWS = {
    "01-capability-map.md": cap_map,
    "02-skill-dependency-graph.md": dep_graph,
    "03-skill-hierarchy.md": hierarchy,
    "04-cross-cutting.md": crosscutting,
    "05-critic-framework.md": critic_matrix,
    "09-radar-legacy-milestones.md": radar_legacy_milestones,
}


def main():
    m = Model()
    check = "--check" in sys.argv
    stale = []
    for name, fn in VIEWS.items():
        text = fn(m)
        path = os.path.join(DOCS, name)
        if check:
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
            if cur != text:
                stale.append(name)
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
    if check:
        if stale:
            print("stale generated docs:", ", ".join(stale))
            sys.exit(1)
        print("generated docs are current")
    else:
        print("rendered:", ", ".join(VIEWS))


if __name__ == "__main__":
    main()
