"""beach_view_evidence.py -- WAVE 18. The three figures for the viewpoint round.

WHAT THIS DRAWS AND WHY IT IS A SEPARATE SCRIPT. The contract's amendment says a
figure is generated by a committed script and never pasted in, "because a figure
nobody can regenerate is a screenshot of a claim, and it will be wrong within
three waves and nobody will know". Wave 16 measured this same patch and shipped
its PNGs with no script; this wave had to rebuild the whole measurement from the
caption prose to get a comparable number. So the estimator lives in
`beach_render` (`hf_sd`, `PLATEAU_PATCH`), the camera repair lives in
`beach_render.viewpoint`, and this file only arranges pixels.

    python3 beach_view_evidence.py [outdir]

Three figures, NO BURNED-IN TEXT (ruling from wave 11's three critics: captions
inside the pixels defeat a blind review). The captions are the `.caption.md`
files beside them.

  s18-land-hero-before   the shipped hero frame, terraced bed, legacy brow
  s18-land-hero-after    the same bed and the same code, corrected brow
  s18-land-patch         rows 620-720 / cols 60-360 of each, at 1:1

ONE EXPOSURE KEY FOR EVERY PANEL (`beach_render.WHITE`), so a difference in the
image is a difference in the radiance and not in the grade. Every number quoted
in the captions is measured on the scene-linear buffer before the tone map.
"""
import os
import sys
import tempfile
import time

import numpy as np
from PIL import Image

import beach as B
import beach_render as R

SS = R.HERO_SS
WW, HH = R.HERO_WH
R0, R1, C0, C1 = R.PLATEAU_PATCH


def brow_legacy(w, y_cam, h_eye):
    """The wave-7..17 brow search. Present so the round can draw its own
    before-frame from its own code rather than from an archived PNG."""
    j = int(np.argmin(np.abs(w.y - y_cam)))
    prof, x = w.h[j], w.x
    slope = np.abs(np.gradient(prof, float(x[1] - x[0])))
    land = prof > 2.0
    ramp = float(np.median(slope[land])) if land.any() else 0.08
    for i in range(x.size - 2, 1, -1):
        if prof[i] <= 2.0:
            break
        if slope[i] > 3.0 * ramp:
            return float(x[i + 1])
    return float('nan')


def hero(w, legacy=False, cache=None):
    """The bar-J hero frame on `w`, through either brow search."""
    if cache and os.path.exists(cache):
        return np.load(cache)
    y_cam = float(w.y[2])
    _L, s_lines = R.surf_line_scale(w)
    D_lines = float(0.5 * (w.y[-1] - w.y[0]))
    az, _b = R.frame_azimuth_J(w, y_cam, R.CAM.portrait_fov(13.0)[1])
    kw = {'x_cam': brow_legacy(w, y_cam, 1.6)} if legacy else {}
    cam, inf = R.build_frame(w, y_cam, R.CAM.J_CONTENT, 'J', az,
                             WW * SS, HH * SS, D_lines, s_lines, **kw)
    t0 = time.time()
    L, _ex = R.render(cam, w, 0.0)
    L = R.downsample(L, SS)
    print('   rendered x_cam=%.0f in %.0f s' % (inf['x_cam'], time.time() - t0),
          flush=True)
    if cache:
        np.save(cache, L)
    return L


def to8(L, key=None):
    k = R.WHITE if key is None else key
    img = np.clip(np.asarray(L, float) / k, 0.0, 1.0) ** (1.0 / 2.2)
    return (img * 255.0 + 0.5).astype(np.uint8)


def stack(panels, gap=6, bg=255):
    """Panels of equal width, stacked 1:1 with a plain separator.

    NO RESAMPLING ANYWHERE. The patch is 300 x 100 and it is shown at 300 x 100;
    a magnified crop would be a claim about pixels that do not exist, and the
    question the figure answers -- is there anything there at all -- is one that
    interpolation can only obscure.
    """
    wd = panels[0].shape[1]
    out = []
    for i, p in enumerate(panels):
        if i:
            out.append(np.full((gap, wd, 3), bg, np.uint8))
        out.append(p)
    return np.concatenate(out, 0)


def main(outdir):
    os.makedirs(outdir, exist_ok=True)
    # The radiance buffers are cached OUTSIDE the repository: three hero frames
    # are about 25 minutes of ray-casting and 130 MB of float64, and neither
    # is not part of this directory. Override with BEACH_EVIDENCE_CACHE.
    cd = os.environ.get('BEACH_EVIDENCE_CACHE',
                        os.path.join(tempfile.gettempdir(), 'beach-s18'))
    os.makedirs(cd, exist_ok=True)
    t0 = time.time()

    print('terraced bed (4 stands, embayed)...', flush=True)
    w4 = R.Water(B.run_bay(embay=True, stands=4))
    L_before = hero(w4, legacy=True, cache=os.path.join(cd, 'before.npy'))
    L_after = hero(w4, legacy=False, cache=os.path.join(cd, 'after.npy'))

    print('un-terraced bed (the frame wave 11 scored 3/10)...', flush=True)
    w0 = R.Water(B.run_bay(embay=True))
    L_ref = hero(w0, legacy=False, cache=os.path.join(cd, 'unterraced.npy'))

    for name, L in (('s18-land-hero-before', L_before),
                    ('s18-land-hero-after', L_after)):
        p = os.path.join(outdir, name + '.png')
        Image.fromarray(to8(L)).save(p)
        print('  %s  %s' % (p, to8(L).shape), flush=True)

    pat = {k: L[R0:R1, C0:C1] for k, L in (('before', L_before),
                                           ('after', L_after),
                                           ('ref', L_ref))}
    fig = stack([to8(pat['ref']), to8(pat['before']), to8(pat['after'])])
    p = os.path.join(outdir, 's18-land-patch.png')
    Image.fromarray(fig).save(p)
    print('  %s  %s' % (p, fig.shape), flush=True)

    print('\nTHE NUMBERS (scene-linear, un-quantised, before the tone map)')
    for k in ('ref', 'before', 'after'):
        sd = R.hf_sd(pat[k])
        print('  %-7s hf sd %.4e / %.4e / %.4e   levels %s'
              % (k, sd[0], sd[1], sd[2], R.display_levels(pat[k])))
    print('  after/before  %.0fx / %.0fx / %.0fx'
          % tuple(R.hf_sd(pat['after']) / R.hf_sd(pat['before'])))
    print('  after/ref     %.2fx / %.2fx / %.2fx'
          % tuple(R.hf_sd(pat['after']) / R.hf_sd(pat['ref'])))
    print('%.0f s' % (time.time() - t0))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1
         else os.environ.get('BEACH_OUT', os.path.join(
             os.path.dirname(os.path.abspath(__file__)), 'evidence')))
