#!/usr/bin/env python3
"""Reproducible G1 round-3 revision: restores data/ to the round-2 commit, applies r3_*.py in name order,
writes gauntlet/round-3/changes.md and dispositions.md. Run from anywhere.

Dispositions: findings that hit a planted seed (seeds.md) are removed; explicit partial/reject/merge verdicts
live in disp.py (OVERRIDES, SEED_HITS); every other finding is 'accept' if a logged change cites it."""
import glob
import importlib
import os
import re
import subprocess
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(FW, "scripts"))
sys.path.insert(0, HERE)

BASE_COMMIT = "fd20381"   # round-2 framework
subprocess.run(["git", "checkout", BASE_COMMIT, "--", "data/"], cwd=FW, check=True)

from edit import Editor  # noqa: E402

try:
    import disp  # noqa: E402
    OVERRIDES, SEED_HITS = disp.OVERRIDES, disp.SEED_HITS
except ImportError:
    OVERRIDES, SEED_HITS = {}, {}

ed = Editor()
parts = sorted(os.path.basename(p)[:-3] for p in glob.glob(os.path.join(HERE, "r3_*.py")))
for name in parts:
    importlib.import_module(name).apply(ed)
ed.save()

tag_index = {}
for tags, text in ed.log:
    for t in re.findall(r"K-[A-Z]+-\d+", tags or ""):
        tag_index.setdefault(t, []).append(text)

findings = []
for fn in sorted(os.listdir(HERE)):
    if fn.startswith("K-") and fn.endswith(".md"):
        for line in open(os.path.join(HERE, fn), encoding="utf-8"):
            mm = re.match(r"### (K-[A-Z]+-\d+) · (\w+) · ([\w-]+)", line)
            if mm:
                findings.append(mm.groups())

rows, unaddressed = [], []
for fid, sev, typ in findings:
    if fid in SEED_HITS and fid not in OVERRIDES:
        if fid in tag_index:
            verdict = "seed+residual"
            note = f"hit planted seed {SEED_HITS[fid]}; residual fixed: " + "; ".join(tag_index[fid][:3])
        else:
            verdict, note = "seed", f"hit planted seed {SEED_HITS[fid]} (removed)"
    elif fid in OVERRIDES:
        verdict, note = OVERRIDES[fid]
        if fid in tag_index and verdict != "reject":
            note += " — " + "; ".join(tag_index[fid][:3])
    elif fid in tag_index:
        verdict, note = "accept", "; ".join(tag_index[fid][:4]) + (" …" if len(tag_index[fid]) > 4 else "")
    else:
        verdict, note = "UNADDRESSED", ""
        unaddressed.append(fid)
    rows.append((fid, sev, typ, verdict, note))

with open(os.path.join(HERE, "changes.md"), "w", encoding="utf-8") as f:
    f.write("# G1 round 3 — change log\n\nGenerated by `apply.py`. Every change cites the finding that motivated it "
            "(round-1 overturns are cited by their round-1 id).\n\n")
    for tags, text in ed.log:
        f.write(f"- {text}" + (f"  _[{tags}]_" if tags else "") + "\n")

with open(os.path.join(HERE, "dispositions.md"), "w", encoding="utf-8") as f:
    cnt = Counter((sev, v) for _, sev, _, v, _ in rows)
    f.write("# G1 round 3 — dispositions\n\nGenerated by `apply.py`. Seed hits are removed before disposition "
            "(PROTOCOL.md, calibration). `partial` and `reject` go to the independent adjudicator.\n\n")
    f.write("| severity | seed | seed+residual | seed/partial | accept | partial | reject | merge | unaddressed |\n"
            "|---|---|---|---|---|---|---|---|---|\n")
    for sev in ("blocker", "major", "minor"):
        f.write(f"| {sev} | " + " | ".join(str(cnt[(sev, v)]) for v in
                ("seed", "seed+residual", "seed/partial", "accept", "partial", "reject", "merge", "UNADDRESSED"))
                + " |\n")
    f.write("\n| Finding | Sev | Type | Disposition | Change / reason |\n|---|---|---|---|---|\n")
    for fid, sev, typ, v, note in rows:
        f.write(f"| {fid} | {sev} | {typ} | {v} | {note.replace('|', '/')} |\n")

print(f"{len(findings)} findings; {len(ed.log)} logged changes; unaddressed: {unaddressed}")
